name: Déploiement de R-Ticket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Exécuter le script de déploiement via SSH
      run: |
        # Secrets GitHub
        SSH_USERNAME=${{ secrets.SSH_USERNAME }}
        SSH_HOST=${{ secrets.SSH_HOST }}
        SSH_PORT=${{ secrets.SSH_PORT }}
        SCRIPT_PATH=${{ secrets.DEPLOY_SCRIPT_PATH }}

        # Connection au serveur et exécution du script
        ssh -p "$SSH_PORT" "$SSH_USERNAME@$SSH_HOST" "$SCRIPT_PATH"

      # Assurez-vous que l'action est déclenchée uniquement lorsque la branche main est poussée
      if: github.ref == 'refs/heads/main'
