name: Déploiement de R-Ticket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Exécuter le script de déploiement
      run: |
        # Utilisez curl pour appeler l'URL du script sur votre serveur
        curl -X POST https://deploy-r-ticket-46gh78f.agtn.fr/deploy-r-ticket-production.sh

      # Assurez-vous que l'action est déclenchée uniquement lorsque la branche main est poussée
      if: github.ref == 'refs/heads/main'
